version: "3.6"

services:
  app:
    tty: true
    restart: always
    networks:
      - app
    container_name: app
    build:
      context: ./node-server
      dockerfile: ./Dockerfile
    ports:
      - "9229:9229"
      - "4001:4001"
    volumes:
      - ./node-server:/app/node-server
      - /app/node_modules
  frontend:
    tty: true
    container_name: frontend
    environment:
      - WEBSOCKETIP=app
    networks:
      - app
    restart: always
    build:
      context: ./react
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app/react
      - /app/node_modules

networks:
  app:
